import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("GPT_API_KEY")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")



GPT4O_ENDPOINT=os.getenv("GPT4O_ENDPOINT")
GPT4O_MINI_ENDPOINT=os.getenv("GPT4O_MINI_ENDPOINT")
GPTO3_MINI_ENDPOINT=os.getenv("GPTO3_MINI_ENDPOINT")
GPT41_ENDPOINT=os.getenv("GPT41_ENDPOINT")

DEEPSEEK_R1_ENDPOINT=os.getenv("DEEPSEEK_R1_ENDPOINT")
DEEPSEEK_V3_ENDPOINT=os.getenv("DEEPSEEK_V3_ENDPOINT")

